### PR TITLE
Fetch game data asynchronously from chess.com

### PR DESCRIPTION
**Pull request by thunder-coding**
This speeds up around 50x for 60+ games which is a huge improvement.

### CODE REVIEW

**Comment by benediktwerner** [comment]
Hm, this seems nice in principle, I'm just wondering, does this not run into rate limits?

**Comment by thunder-coding** [comment]
https://github.com/lichess-org/pgn-mule/commit/ae3d3908b9b17baff0714893c75fedcf562ed942 seems unnecessary. 

JS spec seems to gaurantee that "When using numeric keys, the values are returned in the keys' numerical order".

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

Also note to be added that before this PR, the default behaviour is to preserve the game order as is which is not always sorted by board no in the JSON.

> Hm, this seems nice in principle, I'm just wondering, does this not run into rate limits?

In my testing I ran into more network errors. I never hit any rate limit shockingly. Also interesting point is that during high traffic on the chessdotcom website, Cloudflare proxy gives troubles at times by blocking the connections. Although I only faced this during very initial phases of reverse engineering, when I was just trying to get what the JSON data contains, by using curl.

**Comment by benediktwerner** [comment]
> JS spec seems to gaurantee that "When using numeric keys, the values are returned in the keys' numerical order".

Interesting. I guess in this case, it seems borderline ok but sorting it explicitly still seems clearer and avoids using objects as dictionaries.

> In my testing I ran into more network errors.

So, what happens then? I guess the poll fails and then it succeeds when it runs again after the set interval?

**Comment by thunder-coding** [comment]
> So, what happens then? I guess the poll fails and then it succeeds when it runs again after the set interval?

No it doesn't. The default behaviour for unhandled rejected promises has changed since node 15. Need to work out on what could be done here

**Comment by benediktwerner** [comment]
Well, it throws, no? I think rejections should now be handled properly everywhere if I didn't miss anything. Tbh the HTTP lib is kind of a pain, I guess also wouldn't be a bad idea to switch to something more modern. But I'm mostly wondering how it behaves with the cc server, i.e. whether it just succeeds on the next attempt or possibly leads to more errors.

**Pull request merged**
